### ISSUE TITLE
Bug: "Craft Pro is required to perform this action."

### ISSUE THREAD

**Issue by darylknight** [FoxyCart/foxycart-craft#1]
I've currently got the plugin installed on a Client edition of Craft. When I go to settings and try to update my account information (my Username or Week Start Day for example), I click save and get a PHP error saying "Craft Pro is required to perform this action". I initially contacted Craft support and they identified that the FoxyCart plugin is checking my Craft version when I update my account information. I don't get the error when I disable the plugin. Error attached - let me know if you need any more info!

![image](https://cloud.githubusercontent.com/assets/1250017/7271230/ef67a0e6-e8d9-11e4-96d5-73b7728bef3f.png)

**Comment by adamjudd** [comment]
@darylknight - thanks for providing the details, we'll dig in and see if we can spot where we're being a bit overzealous with our permission checking.

**Comment by adamjudd** [comment]
@darylknight - I'm very sorry for the delay in resolving this for you. I've just made a change to the plugin which should correct this issue for you. Thanks for bringing it to our attention!

**Comment by darylknight** [comment]
Thanks Adam - I'll take a look and let you know if it works.

**Comment by darylknight** [comment]
Thanks Adam, problem solved!
