### ISSUE TITLE
$params not working within listTransactions

### ISSUE THREAD

**Issue by RobErskine** [FoxyCart/foxycart-craft#4]
Hey there,

I recently ran a successful donation platform on foxycart that raised over $15,000, so thanks for that :) One issue I noticed on launch day was that my results were only pulling in the 300 most recent donations, so when a new donation came in, the 301st one would get knocked off, and so on. This messed up our live tally of donations raised, which didn't really upset my client, as she was ecstatic we were raising more money, but I'd still love to get this addressed.

To put a bandaid on this problem, I tried paginating the next 300 results and then merging the array together: 

```
{% set transactions = craft.foxyCart.listTransactions %}
{% set transactionsTwo = craft.foxyCart.listTransactions('pagination_start',300) %}

{% set transactionsMerged = transactions|merge([transactionsTwo]) %}
```

Unfortunately the params from `transactionsTwo` didn't get pulled in, and `transactionsMerged` just ended up being the same 300 entries, just duplicated. I tried multiple different array syntaxes as the `$params`, and even tried to hardcode the `$params` inside the public function `listTransactions` on line 210 of `FoxyCartService.php` to no effect.

Am i missing something silly? Thanks for your help.

**Comment by adamjudd** [comment]
@RobErskine - thanks for bringing this up! Two issues at play. One was the one I just fixed related to params not actually passing through from the templates. The other is a small change to how you're passing the params, It'd be as an array like this instead:

```
{% set transactionsTwo = craft.foxyCart.listTransactions({'pagination_start':300}) %}
```

**Comment by RobErskine** [comment]
Thanks @adamjudd this is much appreciated. I've updated my plugin as well as the array param in my template. Everything is working as expected now :D 👍
